name: Calorie Counter CI  # Название процесса

on:
  push:
    branches: [ "main" ] # Запуск при пуше в основную ветку
  pull_request:
    branches: [ "main" ] # Запуск при создании PR

jobs:
  test:
    runs-on: ubuntu-latest # Используем виртуальную машину с Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Копируем код из репозитория

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 pytest pytest-qt coverage
        # Установка системных библиотек для работы GUI в "безголовом" режиме
        sudo apt-get install -y libxcb-cursor0 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0

    - name: Run tests with Coverage
      env:
        QT_QPA_PLATFORM: offscreen # Важно: запускает GUI-тесты без реального монитора
      run: |
        coverage run -m pytest
        coverage report -m

    - name: Generate Coverage Artifact
      # Сохраняем отчет как артефакт, чтобы его можно было скачать в GitHub
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: .coverage
